
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
env:
  DESIRED_UV_VERSION: 0.6.4

jobs:
  ci_run:
    name: Run CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/$DESIRED_UV_VERSION/uv-installer.sh | sh

      - name: Format check
        run: uv run poe format_check

      - name: Lint
        run: uv run poe lint

      - name: Security audit
        run: uv run poe audit

      - name: Run tests
        run: uv run poe test 

