
name: Release

on:
  workflow_dispatch:

env:
  DESIRED_UV_VERSION: 0.6.4

jobs:
  create_release_draft:
    name: Create release draft
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install uv
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/astral-sh/uv/releases/download/$DESIRED_UV_VERSION/uv-installer.sh | sh

      - name: Build distributions
        run: uv build

      - name: Define version (CalVer YYYY.MM.DD)
        id: define_version
        run: echo "version=$(date +%Y.%m.%d)" >> $GITHUB_OUTPUT

      - name: Create tag
        run: |
          git tag ${{ steps.define_version.outputs.version }} HEAD
          git push origin ${{ steps.define_version.outputs.version }}

      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.define_version.outputs.version }}
          name: ${{ steps.define_version.outputs.version }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          files: dist/
