
name: Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release_draft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Determine version
        id: version
        run: echo "version=${{  github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Create release draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          draft: true
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}